nome = str(input('Qual seu nome completo? ')).strip()
maiuscula = nome.upper()
minuscula = nome.lower()
# letras = len(nome.replace(' ', ''))
letras = len(nome) - nome.count(' ')
primeironome = nome.split()
print('Seu nome com letras maíusculas: {}'.format(maiuscula))
print('Seu nome com letras minusculas: {}'.format(minuscula))
print('Seu nome tem ao todo {} letras'.format(letras))
print('Seu primeiro nome é {} e ele tem {} letras'.format(primeironome[0], len(primeironome[0])))